version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tootiredone/app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    links:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - ${HOME}/postgres-data/postgres/:/var/lib/postgresql/data
    ports:
      - "5432:5432"